### ISSUE TITLE
Cannot connect with Cyanogen (OnePlus One)

### ISSUE THREAD

**Issue by AlmogBaku** [schwabe/ics-openvpn#393] opened 2015-09-16 10:15 UTC
after upgrading the OS version to `Cyanogen OS 12.1-YOG4PAS1N0` Android version `Android 5.1.1` I can't connect to the VPN:

Using the official built from the play store:

```
2015-09-16 12:44:45 Running on A0001 (MSM8974) oneplus, Android API 22, version 0.6.35, official build
2015-09-16 12:44:45 Building configuration…
2015-09-16 12:44:47 started Socket Thread
2015-09-16 12:44:47 P:Initializing Google Breakpad!
2015-09-16 12:44:47 Current Parameter Settings:
2015-09-16 12:44:47   config = '/data/data/de.blinkt.openvpn/cache/android.conf'
2015-09-16 12:44:47   mode = 0
2015-09-16 12:44:47   show_ciphers = DISABLED
2015-09-16 12:44:47   show_digests = DISABLED
2015-09-16 12:44:47   show_engines = DISABLED
2015-09-16 12:44:47   genkey = DISABLED
2015-09-16 12:44:47   key_pass_file = '[UNDEF]'
2015-09-16 12:44:47   show_tls_ciphers = DISABLED
2015-09-16 12:44:47   connect_retry_max = 5
2015-09-16 12:44:47 Connection profiles [0]:
2015-09-16 12:44:47   proto = udp
2015-09-16 12:44:47   local = '[UNDEF]'
2015-09-16 12:44:47   local_port = '[UNDEF]'
2015-09-16 12:44:47   remote = 'node2.rimoto.net'
2015-09-16 12:44:47   remote_port = '2194'
2015-09-16 12:44:47   remote_float = DISABLED
2015-09-16 12:44:47   bind_defined = DISABLED
2015-09-16 12:44:47   bind_local = DISABLED
2015-09-16 12:44:47   bind_ipv6_only = DISABLED
2015-09-16 12:44:47   connect_retry_seconds = 5
2015-09-16 12:44:47   connect_timeout = 10
2015-09-16 12:44:47   socks_proxy_server = '[UNDEF]'
2015-09-16 12:44:47   socks_proxy_port = '[UNDEF]'
2015-09-16 12:44:47   socks_proxy_retry = DISABLED
2015-09-16 12:44:47   tun_mtu = 1500
2015-09-16 12:44:47   tun_mtu_defined = ENABLED
2015-09-16 12:44:47   link_mtu = 1500
2015-09-16 12:44:47   link_mtu_defined = DISABLED
2015-09-16 12:44:47   tun_mtu_extra = 0
2015-09-16 12:44:47   tun_mtu_extra_defined = DISABLED
2015-09-16 12:44:47   mtu_discover_type = -1
2015-09-16 12:44:47   fragment = 0
2015-09-16 12:44:47   mssfix = 1450
2015-09-16 12:44:47   explicit_exit_notification = 0
2015-09-16 12:44:47 Connection profiles END
2015-09-16 12:44:47   remote_random = DISABLED
2015-09-16 12:44:47   ipchange = '[UNDEF]'
2015-09-16 12:44:47   dev = 'tun'
2015-09-16 12:44:47   dev_type = '[UNDEF]'
2015-09-16 12:44:47   dev_node = '[UNDEF]'
2015-09-16 12:44:47   lladdr = '[UNDEF]'
2015-09-16 12:44:47   topology = 1
2015-09-16 12:44:47   tun_ipv6 = DISABLED
2015-09-16 12:44:47   ifconfig_local = '[UNDEF]'
2015-09-16 12:44:47   ifconfig_remote_netmask = '[UNDEF]'
2015-09-16 12:44:47   ifconfig_noexec = DISABLED
2015-09-16 12:44:47   ifconfig_nowarn = ENABLED
2015-09-16 12:44:47   ifconfig_ipv6_local = '[UNDEF]'
2015-09-16 12:44:47   ifconfig_ipv6_netbits = 0
2015-09-16 12:44:47   ifconfig_ipv6_remote = '[UNDEF]'
2015-09-16 12:44:47   shaper = 0
2015-09-16 12:44:47   mtu_test = 0
2015-09-16 12:44:47   mlock = DISABLED
2015-09-16 12:44:47   keepalive_ping = 0
2015-09-16 12:44:47   keepalive_timeout = 0
2015-09-16 12:44:47   inactivity_timeout = 0
2015-09-16 12:44:47   ping_send_timeout = 0
2015-09-16 12:44:47   ping_rec_timeout = 0
2015-09-16 12:44:47   ping_rec_timeout_action = 0
2015-09-16 12:44:47   ping_timer_remote = DISABLED
2015-09-16 12:44:47   remap_sigusr1 = 0
2015-09-16 12:44:47   persist_tun = ENABLED
2015-09-16 12:44:47   persist_local_ip = DISABLED
2015-09-16 12:44:47   persist_remote_ip = DISABLED
2015-09-16 12:44:47   persist_key = DISABLED
2015-09-16 12:44:47   passtos = DISABLED
2015-09-16 12:44:47   resolve_retry_seconds = 1000000000
2015-09-16 12:44:47   resolve_in_advance = ENABLED
2015-09-16 12:44:47   username = '[UNDEF]'
2015-09-16 12:44:47   groupname = '[UNDEF]'
2015-09-16 12:44:47   chroot_dir = '[UNDEF]'
2015-09-16 12:44:47   cd_dir = '[UNDEF]'
2015-09-16 12:44:47   writepid = '[UNDEF]'
2015-09-16 12:44:47   up_script = '[UNDEF]'
2015-09-16 12:44:47   down_script = '[UNDEF]'
2015-09-16 12:44:47   down_pre = DISABLED
2015-09-16 12:44:47   up_restart = DISABLED
2015-09-16 12:44:47   up_delay = DISABLED
2015-09-16 12:44:47   daemon = DISABLED
2015-09-16 12:44:47   inetd = 0
2015-09-16 12:44:47   log = DISABLED
2015-09-16 12:44:47   suppress_timestamps = DISABLED
2015-09-16 12:44:47   machine_readable_output = ENABLED
2015-09-16 12:44:47   nice = 0
2015-09-16 12:44:47   verbosity = 4
2015-09-16 12:44:47   mute = 0
2015-09-16 12:44:47   gremlin = 0
2015-09-16 12:44:47   status_file = '[UNDEF]'
2015-09-16 12:44:47   status_file_version = 1
2015-09-16 12:44:47   status_file_update_freq = 60
2015-09-16 12:44:47   occ = ENABLED
2015-09-16 12:44:47   rcvbuf = 65536
2015-09-16 12:44:47   sndbuf = 65536
2015-09-16 12:44:47   sockflags = 0
2015-09-16 12:44:47   fast_io = DISABLED
2015-09-16 12:44:47   comp.alg = 2
2015-09-16 12:44:47   comp.flags = 1
2015-09-16 12:44:47   route_script = '[UNDEF]'
2015-09-16 12:44:47   route_default_gateway = '[UNDEF]'
2015-09-16 12:44:47   route_default_metric = 0
2015-09-16 12:44:47   route_noexec = DISABLED
2015-09-16 12:44:47   route_delay = 0
2015-09-16 12:44:47   route_delay_window = 30
2015-09-16 12:44:47   route_delay_defined = DISABLED
2015-09-16 12:44:47   route_nopull = DISABLED
2015-09-16 12:44:47   route_gateway_via_dhcp = DISABLED
2015-09-16 12:44:47   allow_pull_fqdn = DISABLED
2015-09-16 12:44:47   management_addr = '/data/data/de.blinkt.openvpn/cache/mgmtsocket'
2015-09-16 12:44:47   management_port = 'unix'
2015-09-16 12:44:47   management_user_pass = '[UNDEF]'
2015-09-16 12:44:47   management_log_history_cache = 250
2015-09-16 12:44:47   management_echo_buffer_size = 100
2015-09-16 12:44:47   management_write_peer_info_file = '[UNDEF]'
2015-09-16 12:44:47   management_client_user = '[UNDEF]'
2015-09-16 12:44:47   management_client_group = '[UNDEF]'
2015-09-16 12:44:47   management_flags = 4390
2015-09-16 12:44:47   shared_secret_file = '[UNDEF]'
2015-09-16 12:44:47   key_direction = 2
2015-09-16 12:44:47   ciphername_defined = ENABLED
2015-09-16 12:44:47   ciphername = 'BF-CBC'
2015-09-16 12:44:47   authname_defined = ENABLED
2015-09-16 12:44:47   authname = 'SHA1'
2015-09-16 12:44:47   prng_hash = 'SHA1'
2015-09-16 12:44:47   prng_nonce_secret_len = 16
2015-09-16 12:44:47   keysize = 0
2015-09-16 12:44:47   engine = DISABLED
2015-09-16 12:44:47   replay = ENABLED
2015-09-16 12:44:47   mute_replay_warnings = DISABLED
2015-09-16 12:44:47   replay_window = 64
2015-09-16 12:44:47   replay_time = 15
2015-09-16 12:44:47   packet_id_file = '[UNDEF]'
2015-09-16 12:44:47   use_iv = ENABLED
2015-09-16 12:44:47   test_crypto = DISABLED
2015-09-16 12:44:47   tls_server = DISABLED
2015-09-16 12:44:47   tls_client = ENABLED
2015-09-16 12:44:47   key_method = 2
2015-09-16 12:44:47   ca_file = '[[INLINE]]'
2015-09-16 12:44:47   ca_path = '[UNDEF]'
2015-09-16 12:44:47   dh_file = '[UNDEF]'
2015-09-16 12:44:47   cert_file = '[[INLINE]]'
2015-09-16 12:44:47   extra_certs_file = '[UNDEF]'
2015-09-16 12:44:47   priv_key_file = '[[INLINE]]'
2015-09-16 12:44:47   pkcs12_file = '[UNDEF]'
2015-09-16 12:44:47   cipher_list = '[UNDEF]'
2015-09-16 12:44:47   tls_verify = '[UNDEF]'
2015-09-16 12:44:47   tls_export_cert = '[UNDEF]'
2015-09-16 12:44:47   verify_x509_type = 0
2015-09-16 12:44:47   verify_x509_name = '[UNDEF]'
2015-09-16 12:44:47   crl_file = '[UNDEF]'
2015-09-16 12:44:47   ns_cert_type = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_ku[i] = 0
2015-09-16 12:44:47   remote_cert_eku = '[UNDEF]'
2015-09-16 12:44:47   ssl_flags = 0
2015-09-16 12:44:47   tls_timeout = 2
2015-09-16 12:44:47   renegotiate_bytes = 0
2015-09-16 12:44:47   renegotiate_packets = 0
2015-09-16 12:44:47   renegotiate_seconds = 3600
2015-09-16 12:44:47   handshake_window = 60
2015-09-16 12:44:47   transition_window = 3600
2015-09-16 12:44:47   single_session = DISABLED
2015-09-16 12:44:47   push_peer_info = DISABLED
2015-09-16 12:44:47   tls_exit = DISABLED
2015-09-16 12:44:47   tls_auth_file = '[[INLINE]]'
2015-09-16 12:44:47   client = ENABLED
2015-09-16 12:44:47   pull = ENABLED
2015-09-16 12:44:47   auth_user_pass_file = '[UNDEF]'
2015-09-16 12:44:47 OpenVPN 2.4-icsopenvpn [git:icsopenvpn_634-601da8f5c2cb21d4] android-14-armeabi-v7a [SSL (OpenSSL)] [LZO] [SNAPPY] [LZ4] [EPOLL] [MH] [IPv6] built on Aug 11 2015
2015-09-16 12:44:47 library versions: OpenSSL 1.0.1l 15 Jan 2015, LZO 2.09
2015-09-16 12:44:47 MANAGEMENT: Connected to management server at /data/data/de.blinkt.openvpn/cache/mgmtsocket
2015-09-16 12:44:47 MANAGEMENT: CMD 'hold release'
2015-09-16 12:44:47 MANAGEMENT: CMD 'bytecount 2'
2015-09-16 12:44:47 MANAGEMENT: CMD 'state on'
2015-09-16 12:44:47 MANAGEMENT: CMD 'proxy NONE'
2015-09-16 12:44:47 Network Status: CONNECTED HSPA+ to MOBILE net.hotm
2015-09-16 12:44:48 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
2015-09-16 12:44:48 Control Channel Authentication: tls-auth using INLINE static key file
2015-09-16 12:44:48 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
2015-09-16 12:44:48 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication
2015-09-16 12:44:48 LZO compression initializing
2015-09-16 12:44:48 Control Channel MTU parms [ L:1542 D:1184 EF:66 EB:0 ET:0 EL:3 ]
2015-09-16 12:44:48 Data Channel MTU parms [ L:1542 D:1450 EF:42 EB:393 ET:0 EL:3 ]
2015-09-16 12:44:48 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1542,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher BF-CBC,auth SHA1,keysize 128,tls-auth,key-method 2,tls-client'
2015-09-16 12:44:48 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1542,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher BF-CBC,auth SHA1,keysize 128,tls-auth,key-method 2,tls-server'
2015-09-16 12:44:48 TCP/UDP: Preserving recently used remote address: [AF_INET]52.28.186.83:2194
2015-09-16 12:44:48 Socket Buffers: R=[163840->131072] S=[163840->131072]
2015-09-16 12:44:48 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2015-09-16 12:44:48 UDP link local: (not bound)
2015-09-16 12:44:48 UDP link remote: [AF_INET]52.28.186.83:2194
2015-09-16 12:44:48 MANAGEMENT: >STATE:1442396688,WAIT,,,
2015-09-16 12:44:48 MANAGEMENT: >STATE:1442396688,AUTH,,,
2015-09-16 12:44:48 TLS: Initial packet from [AF_INET]52.28.186.83:2194, sid=38d32432 a73971f8
2015-09-16 12:44:49 VERIFY OK: depth=1, C=IL, ST=Merkaz, O=Rimoto, OU=R&D, CN=Rimoto CORE Certificate Authority, emailAddress=dev@rimotosoftware.com
2015-09-16 12:44:49 VERIFY OK: depth=0, C=IL, ST=Merkaz, O=Rimoto, OU=Users, CN=node2.rimoto.net
2015-09-16 12:44:50 Data Channel Encrypt: Cipher 'BF-CBC' initialized with 128 bit key
2015-09-16 12:44:50 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
2015-09-16 12:44:50 Data Channel Decrypt: Cipher 'BF-CBC' initialized with 128 bit key
2015-09-16 12:44:50 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
2015-09-16 12:44:50 Control Channel: TLSv1, cipher TLSv1/SSLv3 DHE-RSA-AES256-SHA, 2048 bit RSA
2015-09-16 12:44:50 [node2.rimoto.net] Peer Connection Initiated with [AF_INET]52.28.186.83:2194
2015-09-16 12:44:51 MANAGEMENT: >STATE:1442396691,GET_CONFIG,,,
2015-09-16 12:44:51 SENT CONTROL [node2.rimoto.net]: 'PUSH_REQUEST' (status=1)
2015-09-16 12:44:51 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.7.1.1,route 10.50.0.1,topology net30,ping 10,ping-restart 30,ifconfig 10.50.0.6 10.50.0.5'
2015-09-16 12:44:51 OPTIONS IMPORT: timers and/or timeouts modified
2015-09-16 12:44:51 OPTIONS IMPORT: --ifconfig/up options modified
2015-09-16 12:44:51 OPTIONS IMPORT: route options modified
2015-09-16 12:44:51 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2015-09-16 12:44:51 ROUTE_GATEWAY 127.100.103.119/255.0.0.0 IFACE=lo HWADDR=00:00:00:00:00:00
2015-09-16 12:44:51 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
2015-09-16 12:44:51 MANAGEMENT: >STATE:1442396691,ASSIGN_IP,,10.50.0.6,
2015-09-16 12:44:51 MANAGEMENT: CMD 'needok 'IFCONFIG' ok'
2015-09-16 12:44:51 MANAGEMENT: CMD 'needok 'ROUTE' ok'
2015-09-16 12:44:51 MANAGEMENT: >STATE:1442396691,ADD_ROUTES,,,
2015-09-16 12:44:51 MANAGEMENT: CMD 'needok 'ROUTE' ok'
2015-09-16 12:44:51 MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
2015-09-16 12:44:51 MANAGEMENT: CMD 'needok 'PERSIST_TUN_ACTION' OPEN_BEFORE_CLOSE'
2015-09-16 12:44:51 Opening tun interface:
2015-09-16 12:44:51 Local IPv4: 10.50.0.6/30 IPv6: null MTU: 1500
2015-09-16 12:44:51 DNS Server: 10.7.1.1, Domain: null
2015-09-16 12:44:51 Routes: 0.0.0.0/0, 10.50.0.1/32, 10.50.0.4/30 
2015-09-16 12:44:51 Routes excluded:  
2015-09-16 12:44:51 VpnService routes installed: 0.0.0.0/0 
2015-09-16 12:44:51 Disallowed VPN apps: 
2015-09-16 12:44:51 MANAGEMENT: CMD 'needok 'OPENTUN' ok'
2015-09-16 12:44:51 Initialization Sequence Completed
2015-09-16 12:44:51 MANAGEMENT: >STATE:1442396691,CONNECTED,SUCCESS,10.50.0.6,52.28.186.83
2015-09-16 12:44:52 MANAGEMENT: CMD 'signal SIGINT'
2015-09-16 12:44:52 TCP/UDP: Closing socket
2015-09-16 12:44:52 Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2015-09-16 12:44:52 Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2015-09-16 12:44:52 Closing TUN/TAP interface
2015-09-16 12:44:54 SIGINT[hard,] received, process exiting
2015-09-16 12:44:54 MANAGEMENT: >STATE:1442396694,EXITING,SIGINT,,
```

While trying to debug I found the following output by the logs(but it didn't appeared in the official built logs screen):

```
[Sep 16, 12:03:09] [INFO] MANAGEMENT: CMD 'needok 'PERSIST_TUN_ACTION' OPEN_BEFORE_CLOSE'
[Sep 16, 12:03:09] [INFO] Log (no context) resid 2131230982
[Sep 16, 12:03:09] [INFO] Log (no context) resid 213123098410.50.0.10|30|null|1500
[Sep 16, 12:03:09] [INFO] Log (no context) resid 213123092610.7.1.1|null
[Sep 16, 12:03:09] [INFO] Log (no context) resid 21312310430.0.0.0/0, 10.50.0.1/32, 10.50.0.8/30|
[Sep 16, 12:03:09] [INFO] Log (no context) resid 2131231042|
[Sep 16, 12:03:09] [DEBUG] Log (no context) resid 21312310410.0.0.0/0|
[Sep 16, 12:03:09] [DEBUG] Log (no context) resid 2131230923
[Sep 16, 12:03:09] [ERROR] Log (no context) resid 2131231095
[Sep 16, 12:03:09] [ERROR] Error: Android establish() method returned null (Really broken network configuration?)
[Sep 16, 12:03:09] [INFO] MANAGEMENT: CMD 'needok 'OPENTUN' cancel'
[Sep 16, 12:03:09] [WARNING] MGMT: Got unrecognized command>FATAL:ERROR: Cannot open TUN
[Sep 16, 12:03:09] [INFO] MANAGEMENT: Client disconnected
[Sep 16, 12:03:09] [INFO] ERROR: Cannot open TUN
[Sep 16, 12:03:09] [INFO] Exiting due to fatal error
[Sep 16, 12:03:09] [ERROR] Process exited with exit value 1
```

**Comment by schwabe** [comment] 2015-09-16 11:13
You should look into adb logcat or similar. Also log messages that with just ressource Ids are very hard to read, especially since I can only guess the ressource id to string in your custom build app. You might want to try to have a context while logging.

**Comment by AlmogBaku** [comment] 2015-09-16 11:42
@schwabe right.
But for the meanwhile for this issue I pasted the log from your version which include the message...

The problematic section is:

```
[Sep 16, 12:03:09] [ERROR] Error: Android establish() method returned null (Really broken network configuration?)
[Sep 16, 12:03:09] [INFO] MANAGEMENT: CMD 'needok 'OPENTUN' cancel'
[Sep 16, 12:03:09] [WARNING] MGMT: Got unrecognized command>FATAL:ERROR: Cannot open TUN
[Sep 16, 12:03:09] [INFO] MANAGEMENT: Client disconnected
[Sep 16, 12:03:09] [INFO] ERROR: Cannot open TUN
```

**Comment by AlmogBaku** [comment] 2015-09-16 12:01
Something really weird just happened:
After 2 weeks of trying to connect with this device, it suddenly worked!
I tried to connect to some other VPN mechanism which seems to somehow fixed it.. them I revoked the VPN(from the notification status) and tried to conenect again and it worked
My guess is that by tried to connect with OperaMAX VPN, the android first disabled any other vpn connection and flushed the routes.. and it fixes the problem.

Maybe they flushing the routes by the app?

**Comment by xDragonZ** [comment] 2015-09-16 21:21
That's is a known bug for Android 5.0+ devices. 
Refer to Android Issue #80074

**Comment by schwabe** [comment] 2015-11-18 12:17
Since the bug cannot reproduced anymore I am closing this ticket. If you encounter the issue again feel free to open a new ticket.

**Closed as completed by schwabe** 2015-11-18 12:17 UTC

**Comment by AlmogBaku** [comment] 2015-12-06 17:41
@schwabe I can verify that this issue solved (at least from master) :+1:
