### ISSUE TITLE
Client does not reconnect when server is restarted (ping-restart doesn't work?)

### ISSUE THREAD

**Issue by jjakob** [schwabe/ics-openvpn#1175] opened 2020-04-04 13:47 UTC
# General information
1. Android 7.1.2
2. LineageOS 14.1
3. Xiaomi Redmin Note 3
4. F-droid OpenVPN for Android 0.7.15
 
# Description of the issue
When a server restarts or the client loses connection to the server, the connection is never reestablished. I added ping 10 and ping-restart 30 to the custom config, but there is no difference. There are no logs when the connection is lost, just the packets from the server stop coming in (the graph shows packets going out, 0 coming in). This can last for at least 20 minutes (I haven't waited longer) until I manually restart the connection.

[openvpn-config.txt](https://github.com/schwabe/ics-openvpn/files/4431479/openvpn-config.txt)

**Comment by schwabe** [comment] 2020-04-23 12:13
Without a log, this is a hard to debug. Also normally the ping option are pushed by your server so your custom setting are probably overridden and have no effect at all.

**Comment by jjakob** [comment] 2020-04-23 16:50
Thanks for the information, I added `push-filter ignore "ping"` to the custom config, I'll see if that makes a difference. The server-sent ping-restart is very long, so it could be that.

The odd thing is that it doesn't detect the network has changed and reconnect (I thought it was supposed to reconnect if the network changes from e.g. wifi to mobile and vice-versa)

**Comment by schwabe** [comment] 2020-04-24 06:25
Ignoring or have a mismatch in client and server ping will more likely give you a bad experience. If you set your client to ping-restart of 30 and the server has ping 60, you will always reconnect after 30 seconds.

I am closing this issue since it seems to work as intended.

**Closed as completed by schwabe** 2020-04-24 06:25 UTC
