### ISSUE TITLE
Quick settings tile doesn't work after updating to Android 14

### ISSUE THREAD

**Issue by konstantin-uvarov** [schwabe/ics-openvpn#1670] opened 2023-11-16 13:02 UTC
<h1>General information</h1>

Android Version: 14

Device: Samsung S23

Version of the app (version number/play store version/self-built): 0.7.49

<h1>Description of the issue</h1>

After updating a Samsung Galaxy S23 to the latest software (Android 13 => 14, One UI 5.1 => 6.0) the quick settings tile doesn't start a default VPN connection (connection has been setup in the app settings) if the main application hasn't been started preliminary.

If you start the main app window, quick settings tile works as before.

When you remove app from the memory or didn't use it for a while, quick settings tile does nothing when you tap on it.

Before the software update it worked well in both cases.

The video below shows the issue.

https://github.com/schwabe/ics-openvpn/assets/117157551/dc0e3a3e-ea15-4987-9f68-4d20e9459620

**Comment by schwabe** [comment] 2023-11-16 21:08
Duplicate of #1652. Try again with the 0.7.50 that is already in beta.

**Closed as completed by schwabe** 2023-11-16 21:08 UTC
