### ISSUE TITLE
OpenVPN für Android looses connection if Mobilephone is not used

### ISSUE THREAD

**Issue by HeikoGrethe** [schwabe/ics-openvpn#1353] opened 2021-08-15 08:39 UTC
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 10 (and some older versions)
2. Android Vendor/Custom ROM: Samsung - SAOMC_SM-A600FN_ODX_DTM_QQ_0005 52008302bc5f658d
2a. Kernel: 3.18.140-20847361
3. Device: A6 [SM-A600FN] (and some other Samsung/Motorola)
4. Version of the app: OpenVPN für Android 0.7.22
 
# Description of the issue
I'm using OpenVPN für Android to connect Zoiper with our internal PBX. OpenVPN server is IPFire build 158.
System is running very stable since several monthes but since about one week the OpenVPN connection "is going sleeping" when the phone is not used (over night e.g. or during long meetings).

When I pickup the phone (unlock the screen) OpenVPN für Android reconnects the connection after some seconds. But in the meantime Zoiper was not available for the PBX.

I tried to "catch" some logs as long as the system has not reconnected that you can check the situation.
I tried Android setting: "VPN immer eingeschaltet", but that does not help.

Please find attached some logs!

If you have a solution for this, it would help very much! 
I can provide any other information needed!

Many thanks for help in advance!
Heiko Grethe
[OpenVPN für Android - logs.zip](https://github.com/schwabe/ics-openvpn/files/6987782/OpenVPN.fur.Android.-.logs.zip)

**Comment by schwabe** [comment] 2021-08-15 12:59
Hm, the logs all end in the VPN conected or in case of 4th log in an connection. Do you have any point in the logs where the connection is broken?

It might also be Samsung's battery "improvement": https://dontkillmyapp.com/

**Comment by HeikoGrethe** [comment] 2021-08-16 06:59
Any hint, how to build a "trap" for the log?
When I pick the phone, it shows unconnected OpenVPN:
![Screenshot_20210816-084924_Gallery-cropped](https://user-images.githubusercontent.com/88962871/129523353-c1af55ba-39b4-4967-80e2-91c49c55019b.jpg)

Ten seconds later the connection is established:
![Screenshot_20210816-084935_Gallery-cropped](https://user-images.githubusercontent.com/88962871/129523418-7d0f8a4d-54ff-4860-95b0-d1db9946b1f7.jpg)

I tried to catch the log before it connects.

**Comment by HeikoGrethe** [comment] 2021-08-16 07:12
In the meantime I have deactivated the battery optimizing for the App "OpenVPN für Android" as descriped.
https://dontkillmyapp.com/samsung

**Comment by schwabe** [comment] 2021-08-16 10:16
Well just the better description that it is disconnected when then phone is idle and then log is taken immeadiately after the reconnect when this behaviour is seen is helpful. I need to understand what I am looking for the in the log

**Comment by HeikoGrethe** [comment] 2021-08-16 15:58
OK, new (better?) example: 
[2021-08-16 16_55_51.txt](https://github.com/schwabe/ics-openvpn/files/6993650/2021-08-16.16_55_51.txt)

Tried to call Zoiper on Android-Phone at 16:54:39 (PC-Time): no answer signaled on phone line.
Checked Android-Phone (greyed out OpenVPN für Android Icon as above shown).
Checked log file - last entry: _**2021-08-16 16:53:26 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'**_

As you can see next log entry is: _**2021-08-16 16:55:49 TCP connection established with [AF_INET]84.143.19.173:31194**_
But that is after the phone missed the call and I have entered the app "OpenVPN für Android".

I read the log as followed: 1 Minute before missing the call  OpenVPN für Android was active. But it did not establish an connection:
**_2021-08-16 16:53:26 Attempting to establish TCP connection with [AF_INET]84.143.19.173:31194 [nonblock]_**

Same 5 minutes earlier at: **_2021-08-16 16:48:35 Attempting to establish TCP connection with [AF_INET]84.143.19.173:31194 [nonblock]_**
1.15 minutes later the connection is established:
**_2021-08-16 16:50:50 TCP connection established with [AF_INET]84.143.19.173:31194_**

But at: **_2021-08-16 16:53:25 [ipfire.erm-consulting.local] Inactivity timeout (--ping-restart), restarting_**

I searched all log entries with "Attempting to establish TPC connection with ...
Sometimes it takes 0 or 2 seconds to get "TCP connection established with ..."
Sometimes it takes 2 or 4 minutes to get  a connection - e.g.: **_2021-08-16 14:47:09 TCP connection established with [AF_INET]84.143.19.173:31194_**
And sometimes it fails (**_2021-08-16 14:40:40 TCP: connect to [AF_INET]84.143.19.173:31194 failed: Connection timed out_**)

At least this shows, that following https://dontkillmyapp.com/samsung does not help to solve the disconnection.

**Comment by schwabe** [comment] 2021-08-16 21:53
```
2021-08-16 16:53:26 MANAGEMENT: >STATE:1629125606,TCP_CONNECT,,,,,,
2021-08-16 16:53:26 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2021-08-16 16:55:49 TCP connection established with [AF_INET]84.143.19.173:31194
2021-08-16 16:55:49 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2021-08-16 16:55:49 TCP_CLIENT link local: (not bound)
2021-08-16 16:55:49 TCP_CLIENT link remote: [AF_INET]84.143.19.173:31194
2021-08-16 16:55:49 Server poll timeout, restarting
2021-08-16 16:55:49 TCP/UDP: Closing socket
```

Taking this block. This shows the app never even gets the initial answer from the server.  Just the TCP connection is established but nothing else. I might be interesting if there is a service on the phone faking the TCP connection or the server log actually sees a connection attempt. 

An attempt where the app actually gets an answer from the server looks like this:

```
2021-08-16 16:55:50 Attempting to establish TCP connection with [AF_INET]84.143.19.173:31194 [nonblock]
2021-08-16 16:55:50 MANAGEMENT: >STATE:1629125750,TCP_CONNECT,,,,,,
2021-08-16 16:55:50 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2021-08-16 16:55:50 TCP connection established with [AF_INET]84.143.19.173:31194
2021-08-16 16:55:50 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2021-08-16 16:55:50 TCP_CLIENT link local: (not bound)
2021-08-16 16:55:50 TCP_CLIENT link remote: [AF_INET]84.143.19.173:31194
2021-08-16 16:55:50 MANAGEMENT: >STATE:1629125750,WAIT,,,,,,
2021-08-16 16:55:50 MANAGEMENT: >STATE:1629125750,AUTH,,,,,,
2021-08-16 16:55:50 TLS: Initial packet from [AF_INET]84.143.19.173:31194, sid=bc9c3e48 6ac906e4
```

The TLS: initial packet is the first packet from the server.

From log it looks like the app is really struggling to communicate with the VPN server. The app isn't killed and is kept running but fails to have any sensible network communication, which is odd. Does this happen on both Wifi and mobile network or only WiFi?

**Comment by HeikoGrethe** [comment] 2021-08-17 07:32
Until now I have notified the issue during Wifi using.
I will switch off Wifi today and check the situation.

**Comment by HeikoGrethe** [comment] 2021-08-17 15:11
Have tested connection during the day from time to time with long times of not using the phone. Wifi was switched off all the time.
=> all incomming calls reached Zoiper on smartphone.
only one "Attempting to establish TCP connection with [AF_INET]84.143.19.173:31194" => that was when I switched off Wifi.
Please find attached log (contains log entries from yesterday too), I switched at 9:32 this morning
[2021-08-17 15_34_06.txt](https://github.com/schwabe/ics-openvpn/files/7001107/2021-08-17.15_34_06.txt)

**Comment by HeikoGrethe** [comment] 2021-08-18 07:30
24 hours without error without Wifi. I switch Wifi on again. App has reestablished TCP connection. Let's see what happens during the day

**Comment by HeikoGrethe** [comment] 2021-08-22 07:53
Hmm, Mystery or have you changed something?
Since I switched on Wifi again, the connection is always ok. During the last 4 days there was no issue anymore. 
e.g.
2021-08-20 17:10:20 Attempting to establish TCP connection with [AF_INET]84.143.19.173:31194 [nonblock]
2021-08-20 17:10:20 MANAGEMENT: >STATE:1629472220,TCP_CONNECT,,,,,,
2021-08-20 17:10:20 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2021-08-20 17:10:20 TCP connection established with [AF_INET]84.143.19.173:31194
2021-08-20 17:10:20 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2021-08-20 17:10:20 TCP_CLIENT link local: (not bound)
2021-08-20 17:10:20 TCP_CLIENT link remote: [AF_INET]84.143.19.173:31194
2021-08-20 17:10:20 MANAGEMENT: >STATE:1629472220,WAIT,,,,,,
2021-08-20 17:10:20 MANAGEMENT: >STATE:1629472220,AUTH,,,,,,
2021-08-20 17:10:20 TLS: Initial packet from [AF_INET]84.143.19.173:31194, sid=eaa0f672 45ddb15e

**Comment by schwabe** [comment] 2021-08-22 10:59
No, I didn't do anything.

**Comment by schwabe** [comment] 2021-10-01 13:19
I will close this as non reproducible for the time now.

**Closed as completed by schwabe** 2021-10-01 13:19 UTC
Labels: notreproducible
