### ISSUE TITLE
Waiting for usable network with Persistent tunnel enabled

### ISSUE THREAD

**Issue by futurealecks** [schwabe/ics-openvpn#613] opened 2017-01-20 17:40 UTC
# General information
1. Android Version: 7.1.1
2. Android Vendor/Custom ROM: 
3. Device: Nexus 5x
4. Version of the app (version number/play store version/self built): Play store 0.6.64
 
# Description of the issue

While connecting to the openvpn server with persistent tunnel enabled the device sits in "Waiting for usable network". Tested with both cell and wifi service. 

During this process it wont allow you to disconnect/gets stuck in this state.

Logs:

```
2017-01-20 12:34:40 official build 0.6.64 running on google Nexus 
le/bullhead/bullhead:7.1.1/N4F26I/3532671:user/release-keys)
2017-
01-20 12:34:40 Used x 1 tries to get current version (4/4) of the 
ava.lang.InterruptedException: OpenVpn process was killed form jav
rameter Settings:
2017-01-20 12:34:42   config = '/data/user/0/de.
  show_digests = DISABLED
2017-01-20 12:34:42   show_engines = DIS
5X (bullhead), Android 7.1.1 (N4F26I) API 25, ABI arm64-v8a, (goog
profile
2017-01-20 12:34:40 Building configuration…
2017-01-20 12:
ead.run(OpenVPNThread.java:64)
 at java.lang.Thread.run(Thread.jav
seconds = 2
2017-01-20 12:34:42   connect_timeout = 4
2017-01-20 1
received, sending exit notification to peer
2017-01-20 12:34:41 TC
  key_pass_file = '[UNDEF]'
2017-01-20 12:34:42   show_tls_ciphers
34:40 MANAGEMENT: CMD 'signal SIGINT'
2017-01-20 12:34:40 SIGTERM 
blinkt.openvpn/cache/android.conf'
2017-01-20 12:34:42   mode = 0
 12:34:42 Connection profiles [0]:
2017-01-20 12:34:42   proto = u
P/UDP: Closing socket
2017-01-20 12:34:41 Error reading from outpu
2017-01-20 12:34:42   show_ciphers = DISABLED
2017-01-20 12:34:42 
t of OpenVPN process: OpenVpn process was killed form java code

j
ocal_port = '[UNDEF]'
2017-01-20 12:34:42   remote = '52.21.4.216'
2   bind_ipv6_only = DISABLED
2017-01-20 12:34:42   connect_retry_
a code
 at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThread

2017-01-20 12:34:42   remote_port = '9090'
2017-01-20 12:34:42   
Args(OpenVPNThread.java:181)
 at de.blinkt.openvpn.core.OpenVPNThr
remote_float = DISABLED
2017-01-20 12:34:42   bind_defined = DISAB
a:761)

2017-01-20 12:34:42 started Socket Thread
2017-01-20 12:34
LED
2017-01-20 12:34:42   bind_local = DISABLED
2017-01-20 12:34:4
:42 P:Initializing Google Breakpad!
2017-01-20 12:34:42 Current Pa
ABLED
2017-01-20 12:34:42   genkey = DISABLED
2017-01-20 12:34:42 
 = DISABLED
2017-01-20 12:34:42   connect_retry_max = 0
2017-01-20
dp
2017-01-20 12:34:42   local = '[UNDEF]'
2017-01-20 12:34:42   l
2:34:42   socks_prox
```

**Comment by schwabe** [comment] 2017-01-31 12:36
Your log is totally scrabmled. Closing this as it seems to be a duplicate of #612

**Closed as completed by schwabe** 2017-01-31 12:36 UTC
Labels: duplicate
