### ISSUE TITLE
0.6.71+ TLS neg failed soft-tls error

### ISSUE THREAD

**Issue by txtsecusr** [schwabe/ics-openvpn#707] opened 2017-06-26 13:21 UTC
7.1.2 /  Lineage 14.1 / LG G3 D850 / 0.6.72
----------------------------
It hangs at "authenticating" since the update few days ago. VPN server is fine as I can connect on PC. I'm using Angristan's 2.4 openvpn-install script generated configs and it worked well for many months.

TCP/UDP: preserving recently used remote address x.x.x.x:xxxxx
UDP link local: (not bound)
UDP link remote x.x.x.x:xxxxxx
TLS error: TLS key negotation failed to occur within 60 seconds

**Key parameters of config**
remote-cert-tls server
tls-client
tls-cipher TLS-ECHDE-ECDSA-WITH-AES-256-GCM-SHA384
 
**Reverting to 0.6.66 works fine**

**Comment by schwabe** [comment] 2017-06-26 13:55
Check the server logs.

**Comment by aride** [comment] 2017-06-26 13:59
I'm seeing a similar thing. Version 0.6.66 works fine but 0.6.72 cannot connect because it says that the presented server "certificate has expired", which is not true. The server logs show that it's the client who  doesn't continue the connection attempt. Other OpenVPN clients for Windows and Linux continue working normally.

**Comment by aride** [comment] 2017-06-26 14:02
The client log says:

> VERIFY ERROR: depth=1, error=certificate has expired: C=[...snip...]
> OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> TLS_ERROR: BIO read tls_read_plaintext error
> TLS Error: TLS object -> incoming plaintext read error
> TLS Error: TLS handshake failed

**Comment by schwabe** [comment] 2017-06-26 14:20
check that all certificates in the certificate chain have not experied. Maybe your server is sending an outdated cacert.

**Comment by txtsecusr** [comment] 2017-06-26 14:41
**Server log in my case**
TLS error: The server has no TLS ciphersuites in common with the client. Your --tls-cipher setting might be too restrictive.
OpenSSL: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
BIO read tls_read_plaintext error
TLS object -> incoming plaintext read error


TLS cipher specified on the server is the ECDHE, and works well on 0.6.66

**Comment by schwabe** [comment] 2017-06-26 14:45
See the FAQ for SSL SERER HELLO, it is the same issue. Probably openssl 1.1 does not like TLS-ECHDE-ECDSA-WITH-AES-256-GCM-SHA384 anymore

**Comment by txtsecusr** [comment] 2017-06-26 14:47
Will try that. It didn't ring a bell as I had ECDHE working across devices since 2.4 release earlier this year and thought perfected it.

**Comment by schwabe** [comment] 2017-06-26 14:56
when you put show-tls as custom option in the client you will see the supported ciphers. 

Btw. OpenSSL automatically selects the best shared cipher automatically. In my case  ECDHE-RSA-AES256-SHA

**Comment by txtsecusr** [comment] 2017-06-26 15:10
Still getting hello: no shared cipher error
Tried client workaround (tls-cipher "DEFAULT:!EXP:!PSK:!SRP:!kRSA"), as well as removing tls-cipher entirely
Tried server workaround (tls-cipher "DEFAULT:!EXP:!PSK:!SRP:!kRSA"), as well as removing tls-cipher entirely
 *rebooted server after each change as well

Ran --show-tls
TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384 <the one openvpn-install configured for me
TLS-ECDHE-RSA-WITH-AES-256-CBC-SHA384
TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA384
........(continues)

Server is running latest Jessie2.4.3

Sorry I'm not expert if I'm missing something obvious.

**Comment by schwabe** [comment] 2017-06-26 15:12
Try no tls-cipher in both server and client. Current openvpn is setting a fairly secure default for tls-cipher anyway.

**Comment by schwabe** [comment] 2017-06-26 15:54
I am closing the bug. The shared cipher is something that is very OpenSSL specific and not OpenVPN specific. 

The expired certificate is probably some stricter check of OpenSSL 1.1 as well.

**Closed as completed by schwabe** 2017-06-26 15:54 UTC

**Comment by aride** [comment] 2017-06-26 16:32
Regarding the expired certificate, I've been looking into it and it's caused by a changed OpenVPN behaviour in the latest version. Although the client receives valid (non-expired) certificates, this problem is caused by the presence of **extra** certificates in the chain which have expired.

Thus, version 0.6.72 fails with the following:

> client CA chain (inline): valid CA + expired intermediate authority for clients + expired intermediate authority for servers
> client cert chain (inline): valid client certificate + valid intermediate authority for clients + valid CA
> server CA chain: valid CA
> server cert chain: valid server certificate + valid intermediate authority for servers + valid CA

But it works with:

> client CA chain (inline): valid CA
> client cert chain (inline): valid client certificate + valid intermediate authority for clients + valid CA
> server CA chain: valid CA
> server cert chain: valid server certificate + valid intermediate authority for servers + valid CA

OTOH, version 0.6.66 works in both scenarios.

Now, I'm not sure this can be clearly labeled as a bug on OpenVPN's part since those extra expired certificates shouldn't be there in normal operation, but I think it **could** be seen as a bug because such extra expired certificates can sometimes be left there on purpose while renewing them in order to let the client pick the certificate that best satisfies its verification requirements. Without keeping these expired certificates around for a while, I'm not sure how one could ensure continued operation during a certificate renewal (apart from having an overlap period when two certificates are valid simultaneously, which might not be desirable). What do you think?

**Comment by schwabe** [comment] 2017-06-26 16:40
Well that certificate validaty checking is outside openvpn's scope and done by OpenSSL itself. If you want to change/argue about it, you probably have to convince OpenSSL itself. OpenVPN will not implement any logic to change OpenSSL's logic. And good luck arguing with the OpenSSL project.

But generally client and server should send their intermediate certificates. And the server/client server certificate should be not valid long than the intermediate anyway.

**Comment by aride** [comment] 2017-06-26 16:51
> good luck arguing with the OpenSSL project.

LOL thanks.
