### ISSUE TITLE
Since latest Android Update OpenVPN 0.7.25 doesn't work (Java error)

### ISSUE THREAD

**Issue by Quikfix73** [schwabe/ics-openvpn#1372] opened 2021-10-05 21:17 UTC
I do tech support for a living and I use OpenVPN to signup to a number of different companies like HMA VPN and IPVanish, etc and I noticed after today's update to the latest OpenVPN for Android version 0.7.25 no connections will work and I keep getting JAVA errors in the log no matter what connection I use.  (refer to attached screenshots)

Everything worked fine until I updated to latest version so look at my screenshots.

I am on Android TV version 9

Also, whether you have the option below turned on or not you get the same Java configuration error

OpenVPN 3 Core
Use OpenVPN 2.x

![2](https://user-images.githubusercontent.com/75220145/136103948-d00c03b2-0985-476f-8ee7-cb74a9e146a2.jpg)
![3](https://user-images.githubusercontent.com/75220145/136103953-91b95f40-4332-4469-a9ad-fd9203d070e8.jpg)
![1](https://user-images.githubusercontent.com/75220145/136103956-b9569514-fa4c-4f6c-9254-a68a57f213ad.jpg)

**Comment by schwabe** [comment] 2021-10-05 21:38
Please look at the open issues (duplicate of #1370 )

**Closed as completed by schwabe** 2021-10-05 21:38 UTC
Labels: duplicate
