### ISSUE TITLE
exit value 7

### ISSUE THREAD

**Issue by kintaro1981** [schwabe/ics-openvpn#947] opened 2018-10-01 14:13 UTC
# General information
1. Android Version
It seems a Lollipop, so 5.x
2. Android Vendor/Custom ROM
Amazon Fire OS 5.2.6.6
3. Device
FireTV Stick
4. Version of the app (version number/play store version/self-built)
 0.7.6 (downloaded from http://plai.de/android/)

# Description of the issue

The connection is estabilished and then after some seconds the process close with exit value 7. 

Client Configuration file:

```
remote x.x.x.x 1194
proto udp
ns-cert-type server

client
dev tun
resolv-retry infinite
keepalive 10 120
nobind
comp-lzo
verb 3

;user nobody
;group nogroup

<ca>
-----BEGIN CERTIFICATE-----
BLAHBLAHBLAH
-----END CERTIFICATE-----
</ca>

key-direction 1
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
BLAHBLAHBLAH
-----END OpenVPN Static key V1-----
</tls-auth>

<cert>
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=CA, L=San Francisco, O=TurnKey Linux, OU=OpenVPN, CN=server/name=openvpn/emailAddress=username@gmail.com
        Validity
            Not Before: Sep 10 09:08:11 2018 GMT
            Not After : Sep  7 09:08:11 2028 GMT
        Subject: C=US, ST=CA, L=San Francisco, O=TurnKey Linux, OU=OpenVPN, CN=username/name=openvpn/emailAddress=username@gmail.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    BLAHBLAHBLAH
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            Netscape Comment: 
                Easy-RSA Generated Certificate
            X509v3 Subject Key Identifier: 
                xxxxxx
            X509v3 Authority Key Identifier: 
                keyid:xxxxxxxx
                DirName:/C=US/ST=CA/L=San Francisco/O=TurnKey Linux/OU=OpenVPN/CN=server/name=openvpn/emailAddress=username@gmail.com
                serial:xxxxxxxxx

            X509v3 Extended Key Usage: 
                TLS Web Client Authentication
            X509v3 Key Usage: 
                Digital Signature
            X509v3 Subject Alternative Name: 
                DNS:godlo
    Signature Algorithm: sha256WithRSAEncryption
         BLAHBLAHBLAH

-----BEGIN CERTIFICATE-----
BLAHBLAHBLAH
-----END CERTIFICATE-----
</cert>

<key>
-----BEGIN PRIVATE KEY-----
BLAHBLAHBLAH
-----END PRIVATE KEY-----
</key>

```

**Comment by schwabe** [comment] 2018-10-01 14:18
Please also include the log. Seeing that you have comp-lzo in your config, this is a duplicate of #944

**Closed as completed by schwabe** 2018-10-01 14:18 UTC
Labels: duplicate
