### ISSUE TITLE
implement PanicKit support

### ISSUE THREAD

**Issue by grrrrr** [schwabe/ics-openvpn#1461] opened 2022-02-27 15:53 UTC
It would be really useful to have [PanicKit](https://github.com/guardianproject/PanicKit) support added to the openvpn app

This would allow the user to trigger (e.g. with [Ripple](https://github.com/guardianproject/ripple)) a destructive or non destructive response in a "panic" situation where a device may be at risk of being taken and being used to access end points over a VPN for example if someone is using the app to access work/office networks  

More details on PanicKit: https://guardianproject.info/code/panickit/

**Comment by schwabe** [comment] 2022-02-27 18:17
I never heard of PanicKit and looking on the github that project seems to be dead as the last commit was 3 years ago.

**Comment by grrrrr** [comment] 2022-02-27 19:03
I think not to much dead as not much need for constant change.  It does what is intended.   maybe @eighthave or @n8fr8 could clarify?

**Comment by eighthave** [comment] 2022-02-28 11:39
Yes indeed.  PanicKit was designed to be simple and maintainable.  So far, it 
hasn't needed an update.  I imagine it will remain so unless Android changes to 
restrict the Intents in a way that breaks the current functionality.

**Comment by schwabe** [comment] 2022-02-28 11:48
Thanks, @eighthave for clarifying. Most projects without a commit in 3 years are dead. That being said. I am not against including panickit support but it is also not high on my todo list either. But PRs are weclome.

**Comment by eighthave** [comment] 2022-02-28 12:14
It is included in a number of apps, including:
* Signal - https://github.com/signalapp/Signal-Android/pull/5550
* CalyxOS - https://gitlab.com/CalyxOS/calyxos/-/issues/72
* F-Droid - https://gitlab.com/fdroid/fdroidclient/-/merge_requests/?scope=all&state=merged&search=panic

**Comment by schwabe** [comment] 2022-03-16 09:55
Closing this as I will not implement it myself but as I said, PRs are welcome.

**Closed as completed** 2022-03-16 09:54 UTC
Labels: Feature Request
