### ISSUE TITLE
FireTV: hangs on "Generating configuration"

### ISSUE THREAD

**Issue by Donderda** [schwabe/ics-openvpn#1629] opened 2023-07-30 18:00 UTC
# General information
1. FireTV OS 5.2.7.4 / Android 5.5.1(?)
4. 0.7.48
 
# Description of the issue
Cannot establish connection with this version. It hangs on "Generating configuration". It looks like something crashes due to a missing function 🙃 
# Log (if applicable)

```
I/ActivityManager( 1844): START u0 {flg=0x20000 cmp=de.blinkt.openvpn/.activities.LogWindow} from uid 10039 on display 0
W/ActivityManager( 1844): Input dispatching paused for current ActivityRecord: ActivityRecord{31923c41 u0 de.blinkt.openvpn/.activities.LogWindow t4694}
V/WindowManager( 1844): addAppToken: AppWindowToken{437e727 token=Token{4e5a5e6 ActivityRecord{31923c41 u0 de.blinkt.openvpn/.activities.LogWindow t4694}}} to stack=1 task=4694 at 3
W/EMP.LoggerMetricsFactoryImpl( 1844): EMP.MetricsCollectionAgent:AppUsageReporter:appVersionName=5.1.1-51.6.5.6_user_656639420;DV;1,appCollectionReason=platformKey;DV;1,appVersionCode=22;DV;1,Product_Mode=DEFAULT;DV;1,appUsageCollection=required;DV;1,durationMS=3509;DV;1,startTimeEpoch=1690736511225;DV;1,launchCount=1;DV;1,appPackageName=com.android.vpndialogs;DV;1,page-type=AppUsageStats;CK;1,hitType=appAction;CK;1,team-name=KindleFramework;CK;1,site_variant=KindleApplication;CK;1,page-action=DISPLAY_USAGE;CK;1,RequestId=09F7C49CE4149B52597F;DV;1:NA
--------- beginning of crash
E/AndroidRuntime( 6679): FATAL EXCEPTION: OpenVPNServiceCommandThread
E/AndroidRuntime( 6679): Process: de.blinkt.openvpn:openvpn, PID: 6679
E/AndroidRuntime( 6679): java.lang.NoSuchMethodError: No static method getMinPeriodMillis()J in class Landroid/app/job/JobInfo; or its super classes (declaration of 'android.app.job.JobInfo' appears in /system/framework/framework.jar)
E/AndroidRuntime( 6679): 	at de.blinkt.openvpn.core.keepVPNAlive.scheduleKeepVPNAliveJobService(keepVPNAlive.java:91)
E/AndroidRuntime( 6679): 	at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:597)
E/AndroidRuntime( 6679): 	at de.blinkt.openvpn.core.OpenVPNService.lambda$onStartCommand$1(OpenVPNService.java:528)
E/AndroidRuntime( 6679): 	at de.blinkt.openvpn.core.OpenVPNService.$r8$lambda$IpnoXQuUdAqLyN_KkgVN5F6PdZY(OpenVPNService.java)
E/AndroidRuntime( 6679): 	at de.blinkt.openvpn.core.OpenVPNService$$ExternalSyntheticLambda2.run(D8$$SyntheticClass)
E/AndroidRuntime( 6679): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 6679): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6679): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6679): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/AndroidRuntime( 6679): To Report FATAL to activityManagerService
V/WindowManager( 1844): Adding window Window{1b091ded u0 de.blinkt.openvpn/de.blinkt.openvpn.activities.LogWindow} at 4 of 4 (after Window{37756c86 u0 com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog})
I/ActivityManager( 1844): addErrorToDropBox inserted hashcode=535a02f262e7ce79ebb42361093c16282b8f72de for eventType crash.
I/AndroidRuntime( 6679): Finished reporting FATAL to activityManagerService
I/WindowState( 1844): WIN DEATH: Window{3cd639b7 u0 Toast}
I/CrashDescriptorUtil( 1844): addErrorToCommonLog Hash already present in file
I/ActivityManager( 1844): Process de.blinkt.openvpn:openvpn (pid 6679) has died
D/ActivityManager( 1844): cleanUpApplicationRecord -- 6679
W/ActivityManager( 1844): Scheduling restart of crashed service de.blinkt.openvpn/.core.OpenVPNService in 1000ms
W/ActivityManager( 1844): Scheduling restart of crashed service de.blinkt.openvpn/.core.OpenVPNStatusService in 11000ms
```

# Configuration file

```
dev tun
tls-client

remote my-host.tld 1194

# The "float" tells OpenVPN to accept authenticated packets from any address,
# not only the address which was specified in the --remote option.
# This is useful when you are connecting to a peer which holds a dynamic address
# such as a dial-in user or DHCP client.
# (Please refer to the manual of OpenVPN for more information.)

#float

# If redirect-gateway is enabled, the client will redirect it's
# default network gateway through the VPN.
# It means the VPN connection will firstly connect to the VPN Server
# and then to the internet.
# (Please refer to the manual of OpenVPN for more information.)

#redirect-gateway def1

# dhcp-option DNS: To set primary domain name server address.
# Repeat this option to set secondary DNS server addresses.

#dhcp-option DNS DNS_IP_ADDRESS

pull

# If you want to connect by Server's IPv6 address, you should use
# "proto udp6" in UDP mode or "proto tcp6-client" in TCP mode
proto tcp-client

script-security 2


comp-lzo

reneg-sec 0

cipher AES-256-CBC

auth SHA512

auth-user-pass
<ca>
-----BEGIN CERTIFICATE-----
TRUNCATED
-----END CERTIFICATE-----

</ca>
```
p.s. it works with the `ics-openvpn-latest-stable.apk`.

**Comment by schwabe** [comment] 2023-08-01 08:50
Duplicate of #1619

**Closed as completed by schwabe** 2023-08-01 08:50 UTC
Labels: duplicate
