### ISSUE TITLE
To add option for 4G network

### ISSUE THREAD

**Issue by komple** [schwabe/ics-openvpn#664] opened 2017-04-27 22:24 UTC
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. 7
2. HTC
3. M9
4. Version 0.6.65
 
# Description of the issue

It will be very helpful to have option thst when always on vpn or connect on boot options is excited to have one more option but to connect to von when on 4G, only to connect to vpn when wifi is on. Like some other apps have option only on wifi.
Thanks.

**Comment by schwabe** [comment] 2017-04-27 22:41
Duplicate of the wifi issue.

**Closed as completed by schwabe** 2017-04-27 22:41 UTC

**Comment by komple** [comment] 2017-04-28 14:18
Which wifi issue?

**Comment by schwabe** [comment] 2017-04-28 14:21
[attachment=9683]

**Comment by schwabe** [comment] 2017-04-28 14:21
#370

**Comment by komple** [comment] 2017-04-28 18:16
Didn't see that one, thanks.
It is great idea to have conditions, can exclude home network.
