### ISSUE TITLE
i can not disconnect before connect to server (openvpn 3)

### ISSUE THREAD

**Issue by xeciyu** [schwabe/ics-openvpn#1045] opened 2019-06-07 06:55 UTC
# General information
1. 7.1 & 6
2. 
3. different device
4. 0.7.8
 
# Description of the issue

this issue related to openvpn 3

i can not disconnect 'connecting process' before connected to server 
for example i can not disconnect if wi-fi or data are off , i should close app and force stop and again tap to connect.

**Comment by schwabe** [comment] 2019-06-07 08:23
I cannot reproduce this. Can you give a more detailed steps how to reproduce this and logs?

**Comment by xeciyu** [comment] 2019-06-07 10:15
example: i can not disconnect process when get [this error](https://github.com/schwabe/ics-openvpn/issues/1043) 
i tap on server name and select disconnect but it is show _building configuration..._ still

**Comment by schwabe** [comment] 2019-06-07 10:44
If that is already in another issue then I am closing this as duplicate

**Closed as completed by schwabe** 2019-06-07 10:44 UTC
