### ISSUE TITLE
Connection issue with existing profile

### ISSUE THREAD

**Issue by Donpichol** [schwabe/ics-openvpn#1376] opened 2021-10-06 18:29 UTC
# General information
1. Android Version --> 10 - Kernel version 4.19.75
2. Android Vendor/Custom ROM --> Unknown 
3. Device --> Sony BRAVIA 4K VH2
4. Version of the app (version number/play store version/self-built) --> Play store 0.7.25
 
# Description of the issue

I suspect I was using an earlier version as 0.7.25 has been released two days ago. My profile was working fine with earlier version.
Now, when trying to connect my profile it ends up with a "java.io.EOFException"

See log

![IMG_20211006_193034](https://user-images.githubusercontent.com/92053160/136262411-85fb1bee-fabf-4f30-b832-a50bf8ab4441.jpg)
![IMG_20211006_193016](https://user-images.githubusercontent.com/92053160/136262432-b326a092-7a6c-4812-b335-ac6651c559fb.jpg)

**Comment by schwabe** [comment] 2021-10-06 19:32
Duplicate of #1370

**Closed as completed by schwabe** 2021-10-06 19:32 UTC
Labels: duplicate, Android TV
