### ISSUE TITLE
Compile error,instruction requires: neon

### ISSUE THREAD

**Issue by jh531207323** [schwabe/ics-openvpn#776] opened 2017-10-20 03:20 UTC
Hi
 Whenever I compile the project on Windows or centos, I have the following error.
how can i fix it. thanks .
  
 
![image](https://user-images.githubusercontent.com/15181617/31803811-65cd3746-b588-11e7-9058-c85e007114ef.png)

**Comment by schwabe** [comment] 2017-10-20 06:28
Duplicate of #774

**Closed as completed by schwabe** 2017-10-20 06:28 UTC

**Comment by jh531207323** [comment] 2017-10-20 06:32
thanks a lot
