### ISSUE TITLE
Missing APK signature V2 (v0.7.16+ can't be installed on Android 11)

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [schwabe/ics-openvpn#1230] opened 2020-09-09 11:21 UTC
After updating to Android 11, I've noticed that OpenVPN app has disappeared from my Google Pixel device. I tried reinstalling it from both F-Droid (v0.7.17a) and Google Play (v0.7.16), but ended up getting non-descriptive error messages. However, v0.7.15 from F-Droid installed with no errors and even somehow restored the settings that I had prior to the OS update. I then uninstalled it completely and tried 0.7.17a again, but still got the same error.

**Comment by nbmrjuhneibkr** [comment] 2020-09-09 11:51
And now I can install 0.7.16, but still can't install 0.7.17a. Weird.

**Comment by schwabe** [comment] 2020-09-09 12:16
what error message are you getting?

**Comment by nbmrjuhneibkr** [comment] 2020-09-09 13:12
It simply says "Install failed due to unknown error". I would blame Google and try resetting my device, but OpenVPN is the only app that I'm having this issue with, and older versions install just fine.

**Comment by schwabe** [comment] 2020-09-09 13:21
That is really strange. Maybe adb logcat can reveal something or maybe I can somehow reproduce it.

**Comment by carlphilipp** [comment] 2020-09-10 14:18
I have the same issue, here is the log when I try to install it from f-droid:
```
2020-09-10 09:14:51.372 2654-12987/? I/Finsky: [613] VerifyAppsInstallTask.a(22): Verify: Cannot read archive for file:///data/app/vmdl1410340349.tmp in request id=17, package=de.blinkt.openvpn
2020-09-10 09:14:51.434 639-639/? E/SELinux: avc:  denied  { find } for pid=12184 uid=10234 name=tethering scontext=u:r:permissioncontroller_app:s0:c234,c256,c512,c768 tcontext=u:object_r:tethering_service:s0 tclass=service_manager permissive=0
2020-09-10 09:14:51.436 2654-12987/? I/Finsky: [613] VerifyMissingSplitsInstallTask.c(7): Could not tell if Splits is installed due to null packageInfo for id=17. Assuming not.
2020-09-10 09:14:51.436 2654-12987/? I/Finsky: [613] VerifyMissingSplitsInstallTask.d(1): Assuming split not required due to null packageInfo for id=17
2020-09-10 09:14:51.441 2654-12987/? I/Finsky: [613] VerifyAdvancedProtectionInstallTask.c(1): Verify AP install started
2020-09-10 09:14:51.441 2654-12987/? I/Finsky: [613] VerifyAdvancedProtectionInstallTask.c(2): Allowing install because there are no Advanced Protection users
2020-09-10 09:14:51.448 2654-2654/? I/Finsky: [2] VerifyAdvancedProtectionInstallTask.ir(2): Reported verification result: ALLOW
2020-09-10 09:14:51.448 2654-12987/? I/Finsky: [613] VerifyPerSourceInstallationConsentInstallTask.c(3): PSIC verification started with installer uid: 10010 package name: com.google.android.packageinstaller, originating uid: 10313
2020-09-10 09:14:51.452 2654-12987/? I/Finsky: [613] VerifyPerSourceInstallationConsentInstallTask.c(17): Skipping logging for attempted installation. Experiments for O+ installation logging are disabled.
2020-09-10 09:14:51.453 2654-2654/? I/Finsky: [2] VerifyInstallTask.c(15): Verifying id=17, result=1
2020-09-10 09:14:51.456 2654-2654/? I/Finsky: [2] VerifyInstallTask.ir(6): Verification complete: id=17, package_name=de.blinkt.openvpn
2020-09-10 09:14:51.511 1390-1745/? I/ActivityManager: Force stopping de.blinkt.openvpn appid=10145 user=-1: installPackageLI
2020-09-10 09:14:51.513 1390-1774/? W/PackageManager: Scanning Failed.
    com.android.server.pm.PackageManagerException: No signature found in package of version 2 or newer for package de.blinkt.openvpn
        at com.android.server.pm.PackageManagerService.assertPackageIsValid(PackageManagerService.java:12197)
        at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:11001)
        at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10761)
        at com.android.server.pm.PackageManagerService.installPackagesLI(PackageManagerService.java:16827)
        at com.android.server.pm.PackageManagerService.installPackagesTracedLI(PackageManagerService.java:16198)
        at com.android.server.pm.PackageManagerService.lambda$processInstallRequestsAsync$21$PackageManagerService(PackageManagerService.java:14364)
        at com.android.server.pm.-$$Lambda$PackageManagerService$aXPYjiloRwQataUrx041SxBr5us.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

**Comment by schwabe** [comment] 2020-09-10 14:49
ah thanks. That is indeed helpful, seems my build lack this (https://source.android.com/security/apksigning/v2?hl=en). I will try to figure out what to do.

**Comment by schwabe** [comment] 2020-09-11 11:18
I uploaded a new 0.7.18 version to Play with 5% of all users. If you are lucky you will get that one. It should include a v2 signature.

(closing the issue since it seems to be a very likely solution. If it doesn't help please comment/reopen here)

**Comment by nbmrjuhneibkr** [comment] 2020-09-11 20:26
Is this update going to be available on F-Droid? Or is there something that needs to be changed with the building/signing process on F-Droid? Play store version (0.7.16) was no longer affected by this issue after I reinstalled and uninstalled v0.7.15, but current F-droid release never works.

**Comment by schwabe** [comment] 2020-09-11 21:01
@nbmrjuhneibkr Better to ask that on the F-droid issue tracker. F-droid builds are not done by me but the fdroid team. I am not sure if they use a seperate signing step or not. This might affect all app on F-Droid that already target the newest API (29)/Android 11

**Comment by nbmrjuhneibkr** [comment] 2020-09-11 22:26
I have plenty of other F-Droid apps installed, but OpenVPN is the only one affected by this issue. And, as I mentioned, earlier F-Droid OpenVPN releases install just fine.
I looked at my logs and see the same error messages as @carlphilipp posted.

Anyway, I reported this to F-Droid: https://gitlab.com/fdroid/fdroiddata/-/issues/2159

**Comment by nbmrjuhneibkr** [comment] 2020-09-12 14:17
This issue affects apps that target SDK=30 and are signed with the v1 signature (which is what F-Droid used).
https://gitlab.com/fdroid/fdroidserver/-/issues/827
As far as I understood after briefly looking into this, the fix is already implemented (but may not be deployed yet) by F-Droid, but each affected app will need to be updated for F-Droid to rebuild it.

**Comment by carlphilipp** [comment] 2020-09-12 15:59
Thank @nbmrjuhneibkr for the tip, I was wondering why I did not have the issue with my app, I don't target yet sdk 30.

**Comment by schwabe** [comment] 2020-09-12 21:23
Yeah the issue you linked explain perfectly well why this is a problem. "Fun" fact, Google's own Play Store Console doesn't war you if you upload an apk targetting API 30 and missing v2 singature.

**Comment by nbmrjuhneibkr** [comment] 2020-09-13 03:08
Is Google aware of this issue?

**Comment by schwabe** [comment] 2020-09-13 21:34
@nbmrjuhneibkr maybe but they want you to hand over your signing key/let the signing be done by them, so I don't know if they even care.

**Comment by schwabe** [comment] 2020-09-16 22:09
Should be fixed with the new release

**Closed as completed by schwabe** 2020-09-16 22:09 UTC
