### ISSUE TITLE
Cannot able to change the package's name de.blinkt.openvpn !

### ISSUE THREAD

**Issue by ebayan** [schwabe/ics-openvpn#524] opened 2016-07-22 09:26 UTC
when I change the package's name from de.blinkt.openvpn to another name like de.blinkt.openvpn2 , i've this error message in run time : 
 java.lang.UnsatisfiedLinkError: Native method not found: de.blinkt.openvpn2.core.NativeUtils.getNativeAPI:()Ljava/lang/String;
why??  i try to change this line : 
Java_de_blinkt_openvpn_core_NativeUtils_rsasign to ---> Java_de_blinkt_openvpn2_core_NativeUtils_rsasign
but the error message is still !! can anyone explain me why this error occurs?? 
thanks..

**Comment by schwabe** [comment] 2016-07-22 09:29
duplicate of #493

**Closed as completed by schwabe** 2016-07-22 09:29 UTC
