### ISSUE TITLE
Unable to set custom domain name for certificate verification

### ISSUE THREAD

**Issue by yarda** [schwabe/ics-openvpn#1186] opened 2020-04-27 16:58 UTC
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: Android 10
2. Android Vendor/Custom ROM: Sony
3. Device: Xperia XZ2C
4. Version of the app (version number/play store version/self-built): 0.7.15

# Description of the issue
I have Czech localization, so sorry if the menu/settings description isn't correct.

I am unable to set the custom DN for the certificate verification. Under the connection, authentication/ciphers -> DN verification enabled then it is not possible to edit the Remote certificate DN (RDN). If I click the RDN, it shows the dialog where I can write, but nothing is written, just the whitespaces. If I click the OK (on the keyboard), dialog is closed, but nothing is stored and it stills show the DN for the server, not the custom DN.

**Comment by schwabe** [comment] 2020-04-27 22:23
duplicate of #1160

**Closed as completed** 2020-04-27 22:23 UTC
Labels: duplicate
