### ISSUE TITLE
Android TV, allowed apps

### ISSUE THREAD

**Issue by 2RightM8** [schwabe/ics-openvpn#693] opened 2017-06-15 14:00 UTC
Android version 6.0.1
Android TV
Device: KD-65X8505C
App version 0.6.70

Hi,
my allowed apps fan in the profile editor won't let me choose between the individual apps I want to disallow or allow. It jumps between every 10 app or so. So I can't mark the specific app I want to disallow from using my VPN.

**Comment by namnos470** [comment] 2017-06-23 21:39
Let's see the feet of the multiples.

**Comment by SaxonRix** [comment] 2017-07-31 16:47
Agreed, it's a little clunky on my end too with Nvidia Shield TV. Perhaps a quick temp fix for a bunch of users would be to enable cursor control with gamepad joystick?

**Comment by schwabe** [comment] 2017-08-01 00:41
@SaxonRix no idea how to enable the cusor. Probably it is disabled since the app declares itself to be TV compatible.

**Comment by achnisch** [comment] 2017-09-18 21:22
I am able to select apps on the shield tv (though it's a pretty clunky). However, this doesn't seem to work as whenever I use Netflix for example it's not excluded from the VPN connection and so I can't use it without disconnecting.

Is this a bug or am I missing something?

**Comment by schwabe** [comment] 2017-09-18 21:55
@achnisch what device? It is possible that your device does not implement the per app setting properly.

**Comment by achnisch** [comment] 2017-09-19 07:13
NVidia Shield TV (1st gen), Android 7.0. Is this something that can be fixed with an update or is it impossible to exclude apps on this device? Thanks

**Comment by schwabe** [comment] 2017-09-19 12:31
No if it s broken on the device, the app cannot workaround it. However "Netflix does not work" is a pretty weak test.

**Comment by bigoulours** [comment] 2017-09-29 06:54
Similar problem with a Sony xe80.
I can only mark the first app in the list.
When I go down apps are highlighted but the checkbox (circle) cannot be marked.
VPN working fine though, great app!

**Comment by hapsuuuuuu** [comment] 2018-02-11 19:39
the same problem on mi box 3. like @bigoulours 

this topic has been opened 8 months ago and no change

**Comment by schwabe** [comment] 2018-02-11 22:43
@hapsuuuuuu yes and this is spare time project so things get priority to my own preference and only if I have time for them.

**Comment by loco-python** [comment] 2018-02-25 14:06
aa

**Comment by cowst** [comment] 2019-04-06 21:49
It is possible to select certain applications only, but it used to require a lot of ups downs left right to get the cursor on the desired ones.
Recently (don't know if it's a newer openvpn version or the newer devices - fire tv stick 4k and sony xf90) the left and right are not necessary anymore, which is a step forward.

**Comment by ulao** [comment] 2020-03-11 17:45
I have a shield and I can attach mouse to change sliders but I can not check boxes. Can I edit a file instead? If so what does a "good" line look like?

**Comment by schwabe** [comment] 2020-03-11 21:10
The file is serialised java objects in binary code. I am not sure if you can edit that easily.

**Comment by ulao** [comment] 2020-03-12 23:41
Thx for saving me the trouble. Is openVPN still active, any hope of getting that option navigable? I guess I could put it on my phone, edit with touch, save that files, and over right it on the shield, then make my other edits but I'm thinking that is going to be a pain. I guess I can try a VNC client.

**Comment by schwabe** [comment] 2020-03-13 09:58
I looked into the issue but there something really strange going on. The onClick event is not firing for the list item since updating the support libraries. It is not an easy fix although it should be.

**Comment by ulao** [comment] 2020-03-13 11:13
Oh I thought it was a limitation of the Shield Environment events. So it is broke for all platforms?

**Comment by schwabe** [comment] 2020-03-13 11:21
technically yes but only for non touch usage. Normally you do not use a keyboard/gamepad with a phone or tablet.

**Comment by ulao** [comment] 2020-03-13 11:25
I see, I did try a mouse and the remote(guess that is seen as a keyboard?). I had no luck with VNC, I guess that thing died and I didn't want to fool with those new things. I was going to try a key board but seems like that is out. I could try a joy2touch app I guess.

**Comment by HamedOv** [comment] 2020-03-26 19:38
I've a Sony Android TV, Exclude Apps works perfectly using a mouse and not the remote control the last time I've checked but with the recent release I can not set it using mouse anymore.

**Comment by HamedOv** [comment] 2020-03-26 19:59
I've checked and version 0.7.8 is working perfect using mouse of course!

**Comment by finnzz** [comment] 2020-03-27 02:09
I can confirm on 0.7.15, I can't check off any apps or move the slider on my MiBox S, using the remote.  I don't have a Bluetooth mouse to try.  I have been trying to find an app that would let me use my phone as a Bluetooth touch pad or mouse.  But no luck.  I tried TeamViewer but the tapping function didn't work on AndroidTV.

I'll take any solution, even a convoluted one.

**Comment by finnzz** [comment] 2020-03-27 02:48
Quick follow-up, I found something that works.

CetusPlay, from the Play store let me use my phone as a mouse, and I was able to select the sliders and apps in OpenVPN.

Just download the CetusPlay server receiver on your AndroidTV, and FireTV Universal Remote Android TV (from CetusPlay) on your phone.

Worked on my MiBox S with Pie.

**Comment by snowzach** [comment] 2020-03-30 03:35
On Nvidia shield 0.7.15 version I can't use the Shield app to select an app. I downgraded to 0.7.8 and it worked.

**Comment by Sheugel** [comment] 2020-04-04 16:29
FYI, the method described in this Reddit post by scumb4ll worked for me (with the Shield TV app on smartphone or a physical keyboard/mouse): https://www.reddit.com/r/AndroidTV/comments/fa89r3/openvpn_allowed_apps_not_selectable_in_philips/

**Closed as completed** 2020-05-06 15:42 UTC
