### ISSUE TITLE
VPN is not connecting after uploading android app bundle(.aab) to play store

### ISSUE THREAD

**Issue by sysdev-jay** [schwabe/ics-openvpn#1459] opened 2022-02-22 05:50 UTC
# General information
1. Android Version: 10
2. Xiaomi Phones,Google
3. Redmi note 7 pro
4. Self bundle build, master (0.7.33 Latest)

# Description of the issue
I am using ics-openvpn version 0.7.33 latest one. The app runs fine with .apk. But once I upload to Google play store through .aab then It's not connecting. After installing the app from the play store, opens fine but on connecting throws exceptions. Following exceptions are getting...

Cannot run program "/data/app/com.mycompany.sslvpn-VkwWqlSgj-ZP5zBpQLYGNA== **/lib/arm64/libovpnexec.so": error=2**, No such file or directory

```
Error reading from output of OpenVPN process: 
Cannot run program "/data/app/com.mycompany.sslvpn-VkwWqlSgj-ZP5zBpQLYGNA==**/lib/arm64/libovpnexec.so": error=2**, No such file or directory
java.io.IOException: Cannot run program "/data/app/com.mycompany.sslvpn-VkwWqlSgj-ZP5zBpQLYGNA==/lib/arm64/libovpnexec.so": error=2, No such file or directory
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
at com.mycompany.sslvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:123)
at com.mycompany.sslvpn.core.OpenVPNThread.run(OpenVPNThread.java:65)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.IOException: error=2, No such file or directory
at java.lang.UNIXProcess.forkAndExec(Native Method)
at java.lang.UNIXProcess.(UNIXProcess.java:133)
at java.lang.ProcessImpl.start(ProcessImpl.java:141)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
```

# What so far I have tried:
1. Adding the following to gradle.properties
**android. bundle.enableUncompressedNativeLibs=false**
2. Added this to main Android manifest file: 
<application     **android:extractNativeLibs="true"**     ... >

I will be very thankful to this wonderful and helpful community for your helping hand.
please!

**Comment by schwabe** [comment] 2022-02-22 11:37
Duplicate of #1331

**Closed as completed by schwabe** 2022-02-22 11:37 UTC
