### ISSUE TITLE
  VPN cannot connect again.Please help! Thank you very much!

### ISSUE THREAD

**Issue by qingqingdaxia** [schwabe/ics-openvpn#766] opened 2017-09-27 05:25 UTC
Return process: we successfully connected with the VPN server, open mobile phone flight mode, about 30~60 seconds to open, try to connect to ICE-OPENVPN continuously, we found that a large number of anomalies in the log: "read UDP [ENETUNREACH] Network is unreachable (code=101). The server log does not display any connection to the receiver request. We open the mobile browser, you can access the network properly. It takes about 4-5 minutes before ICE-OPENVPN can connect to the server
The wait process is too long. Is there a way to reduce the time of this process?

For this error, how is the server configured?

Please help! Thank you very much!

**Comment by schwabe** [comment] 2017-09-27 15:32
Duplicate of #765. Annoying will not get you help faster or better.

**Closed as completed by schwabe** 2017-09-27 15:32 UTC
