### ISSUE TITLE
External app permissions not remembered

### ISSUE THREAD

**Issue by palradu** [schwabe/ics-openvpn#1026] opened 2019-04-10 21:19 UTC
1. Android Version: 9.0
2. Android Vendor/Custom ROM: Custom ROM - Lineage OS
3. Device: OnePlus 3T
4. Version of the app (version number/play store version/self-built): Playstore version 0.7.8

Hi,

I installed the latest version of the app and connected to my VPN server. Thing is, I use Tasker to autoconnect/disconnect from my VPN profile using the 'Send intent' option and every time the Tasker profile runs, the app asks me to allow Tasker (or the profile, not really sure) as an external app. And when I go into the app options, under "Clear allowed external apps", it just shows up as "null" and after I close the app and go back in, the option is greyed out. Is there anything that I need to do on my end to fix that? Or is it something that you'd need to fix?

**Comment by schwabe** [comment] 2019-04-12 09:51
Duplicate of #1018

**Closed as completed by schwabe** 2019-04-12 09:51 UTC
Labels: duplicate
