### ISSUE TITLE
DNS Settings are not set

### ISSUE THREAD

**Issue by enko** [schwabe/ics-openvpn#388] opened 2015-08-25 12:29 UTC
On my Server I have this setting:

```
push "dhcp-option DNS 192.168.122.9"
```

But this setting does not seem to be applied. Even when setting the dns server by hand in the settings, this does not seem to be applied.

I discovered this problem that my xmpp client [conversations](https://github.com/siacs/Conversations) cant connect:

```
08-25 12:26:43.887 D/conversations( 6132): tim@boese-ban.de: connecting
08-25 12:26:43.893 D/conversations( 6132): using dns server: 217.237.149.205 to look up boese-ban.de
08-25 12:26:48.972 D/conversations( 6132): tim@boese-ban.de: timeout in dns
08-25 12:26:51.634 D/conversations( 6132): tim@boese-ban.de: error connecting account. try again in 18s for the 1 time
```

I'm running Android 5.1.1 if that helps. If you need any other information please say so.

**Comment by schwabe** [comment] 2015-08-25 13:43
Please provide a log from the client. I suspect that the XMPP client is using getprop and custom (i.e. a duplicate of #377)

**Comment by schwabe** [comment] 2015-08-25 13:47
A quick search reveals that this is exactly the case. See https://github.com/rtreffer/minidns/issues/12 (the dns library conversations uses)

**Closed as completed by schwabe** 2015-08-25 13:47 UTC
