### ISSUE TITLE
Add a blacklist of network OpenVPN should not try to connect the VPN.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schwabe/ics-openvpn#103] opened 2015-03-19 12:12 UTC
```
I use OpenVPN to keep my phone connected to my home network while connected to 
my work WiFi or my friend's Wifi or using my mobile network.
ics-openvpn works quite reliably.

The problems is when I arrive home: the phone connects to one my home Wifi 
networks (I have two) and ics-openvpn tries to connect to the VPN but it does 
not succeed (but, due to the way things are configured it can't connect, so 
this is ok). The problem is that it keeps trying.

I think the solution should be having a blacklist so when connected to my wifi 
it does not try to connect the VPN.

Thanks
A.
```

Original issue reported on code.google.com by `besang...@grumulla.net` on 1 Nov 2012 at 3:39

**Comment by schwabe** [comment] 2015-07-02 09:04
Duplicate of #370

**Closed as completed by schwabe** 2015-07-02 09:04 UTC
Labels: duplicate, Bug
