### ISSUE TITLE
VPN does not switch between IPv4 and IPv6 transport when needed

### ISSUE THREAD

**Issue by dave4445** [schwabe/ics-openvpn#1546] opened 2022-10-09 13:25 UTC
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
11
3. Android Vendor/Custom ROM
e/OS
5. Device
Pixel 4a
7. Version of the app (version number/play store version/self-built)
 0.7.41

# Description of the issue

When switching between transport networks that have different address families, the app doesn't switch as needed.

For example if mobile connection has both IPv4 and IPv6, but the WiFi only has IPv4, the app gets stuck trying to use IPv6 over the WiFi and never succeeds in connecting when dynamically switching from mobile network to WiFi.

It appears whatever address family was used at time of connection is used forever until a manual reconnect is performed.

The app should detect this and reconnect when needed using the appropriate address family

There are 2 ways to workaround this issue:
1. Open app and click 'reconnect' whenever connecting to a WiFi without IPv6 (this is impractical)
2. Force the VPN to always use IPv4 on all networks by adding 'proto udp4' custom option (this is undesirable)

**Comment by schwabe** [comment] 2022-10-09 13:45
duplicate of #761

**Closed as completed by schwabe** 2022-10-09 13:45 UTC
Labels: duplicate

**Comment by dave4445** [comment] 2022-10-09 13:48
Doh, apparently I'm too good at reporting this issue.

**Comment by schwabe** [comment] 2022-10-09 13:48
yeah, I was surprised that it was the same submitter %)
