### ISSUE TITLE
Build command failed. Error while executing process

### ISSUE THREAD

**Issue by DavidSonNguyen** [schwabe/ics-openvpn#889] opened 2018-06-11 10:29 UTC
Build command failed.
Error while executing process C:\Users\gnvis\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\gnvis\Desktop\de.blinkt.openvpn_158_src\de.blinkt.openvpn_158_src.tar.gz\main\.externalNativeBuild\cmake\noovpn3Debug\x86_64 --target ovpn3}
[1/81] Building C object CMakeFiles/lz4.dir/lz4/lib/lz4.c.o
[2/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/aes.c.o
[3/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/aesni.c.o
[4/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/arc4.c.o
[5/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/entropy_poll.c.o
[6/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/ecdh.c.o
[7/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/cipher.c.o
[8/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/ccm.c.o
[9/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/cmac.c.o
[10/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/ecp.c.o
[11/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/bignum.c.o
[12/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/ecjpake.c.o
[13/81] Linking C static library liblz4.a
[14/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/des.c.o
[15/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/ecdsa.c.o
[16/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/camellia.c.o
[17/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/dhm.c.o
[18/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/error.c.o
[19/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/blowfish.c.o
[20/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/gcm.c.o
[21/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1write.c.o
[22/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/ctr_drbg.c.o
[23/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/base64.c.o
[24/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/ecp_curves.c.o
[25/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1parse.c.o
[26/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/entropy.c.o
[27/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/cipher_wrap.c.o
[28/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/pkcs12.c.o
[29/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/memory_buffer_alloc.c.o
[30/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/md4.c.o
[31/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/oid.c.o
[32/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/pkwrite.c.o
[33/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/pk.c.o
[34/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/platform.c.o
[35/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/ripemd160.c.o
[36/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/md_wrap.c.o
[37/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/md5.c.o
[38/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/padlock.c.o
[39/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/rsa.c.o
[40/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/havege.c.o
[41/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/hmac_drbg.c.o
[42/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/pk_wrap.c.o
[43/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/md.c.o
[44/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/pkcs5.c.o
[45/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/pkparse.c.o
[46/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/pem.c.o
[47/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/md2.c.o
[48/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/sha1.c.o
[49/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/sha256.c.o
[50/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/version.c.o
C:\Users\gnvis\Desktop\de.blinkt.openvpn_158_src\de.blinkt.openvpn_158_src.tar.gz\main\src\main\cpp\mbedtls\library\pkcs5.c:232:25: warning: comparison 'unsigned int' > 4294967295 is always false [-Wtautological-constant-compare]
    if( iteration_count > 0xFFFFFFFF )
        ~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~
1 warning generated.
[51/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/version_features.c.o
[52/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/timing.c.o
[53/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/threading.c.o
[54/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/sha512.c.o
[55/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/xtea.c.o
[56/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/rsa_internal.c.o
[57/81] Linking C static library mbedtls\library\libmbedcrypto.a
[58/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/x509_csr.c.o
[59/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/x509.c.o
[60/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/pkcs11.c.o
[61/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/x509_create.c.o
[62/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/x509write_csr.c.o
[63/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/x509_crl.c.o
[64/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/x509_crt.c.o
[65/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/x509write_crt.c.o
[66/81] Building C object mbedtls/library/CMakeFiles/mbedx509.dir/certs.c.o
[67/81] Linking C static library mbedtls\library\libmbedx509.a
[68/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/debug.c.o
[69/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/ssl_ciphersuites.c.o
[70/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/ssl_cookie.c.o
[71/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/ssl_ticket.c.o
[72/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/ssl_cache.c.o
[73/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/ssl_srv.c.o
[74/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/ssl_tls.c.o
[75/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/ssl_cli.c.o
[76/81] Building C object mbedtls/library/CMakeFiles/mbedtls.dir/net_sockets.c.o
C:\Users\gnvis\Desktop\de.blinkt.openvpn_158_src\de.blinkt.openvpn_158_src.tar.gz\main\src\main\cpp\mbedtls\library\net_sockets.c:321:37: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                    (void *) &type, &type_len ) != 0 ||
                                    ^~~~~~~~~
C:/Users/gnvis/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include\sys/socket.h:310:92: note: passing argument to parameter '__value_length' here
__socketcall int getsockopt(int __fd, int __level, int __option, void* __value, socklen_t* __value_length);
                                                                                           ^
C:\Users\gnvis\Desktop\de.blinkt.openvpn_158_src\de.blinkt.openvpn_158_src.tar.gz\main\src\main\cpp\mbedtls\library\net_sockets.c:331:80: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                                             (struct sockaddr *) &client_addr, &n );
                                                                               ^~
C:/Users/gnvis/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include\sys/socket.h:300:71: note: passing argument to parameter '__addr_length' here
__socketcall int accept(int __fd, struct sockaddr* __addr, socklen_t* __addr_length);
                                                                      ^
C:\Users\gnvis\Desktop\de.blinkt.openvpn_158_src\de.blinkt.openvpn_158_src.tar.gz\main\src\main\cpp\mbedtls\library\net_sockets.c:339:59: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                        (struct sockaddr *) &client_addr, &n );
                                                          ^~
C:/Users/gnvis/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include\sys/socket.h:334:119: note: passing argument to parameter '__src_addr_length' here
__socketcall ssize_t recvfrom(int __fd, void* __buf, size_t __n, int __flags, struct sockaddr* __src_addr, socklen_t* __src_addr_length);
                                                                                                                      ^
C:\Users\gnvis\Desktop\de.blinkt.openvpn_158_src\de.blinkt.openvpn_158_src.tar.gz\main\src\main\cpp\mbedtls\library\net_sockets.c:374:59: warning: passing 'int *' to parameter of type 'socklen_t *' (aka 'unsigned int *') converts between pointers to integer types with different sign [-Wpointer-sign]
                         (struct sockaddr *) &local_addr, &n ) != 0 ||
                                                          ^~
C:/Users/gnvis/AppData/Local/Android/Sdk/ndk-bundle/sysroot/usr/include\sys/socket.h:309:76: note: passing argument to parameter '__addr_length' here
__socketcall int getsockname(int __fd, struct sockaddr* __addr, socklen_t* __addr_length);
                                                                           ^
4 warnings generated.
[77/81] Linking C static library mbedtls\library\libmbedtls.a
[78/81] Generating ovpncli_wrap.cxx
FAILED: cmd.exe /C "cd /D C:\Users\gnvis\Desktop\de.blinkt.openvpn_158_src\de.blinkt.openvpn_158_src.tar.gz\main\.externalNativeBuild\cmake\noovpn3Debug\x86_64 && C:\Users\gnvis\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe -E make_directory ovpn3 && SWIG_EXECUTABLE-NOTFOUND -outdir ovpn3 -c++ -java -package net.openvpn.ovpn3 -outcurrentdir -IC:/Users/gnvis/Desktop/de.blinkt.openvpn_158_src/de.blinkt.openvpn_158_src.tar.gz/main/src/main/cpp/openvpn3/client -IC:/Users/gnvis/Desktop/de.blinkt.openvpn_158_src/de.blinkt.openvpn_158_src.tar.gz/main/src/main/cpp/openvpn3 C:/Users/gnvis/Desktop/de.blinkt.openvpn_158_src/de.blinkt.openvpn_158_src.tar.gz/main/src/main/cpp/openvpn3/javacli/ovpncli.i"
'SWIG_EXECUTABLE-NOTFOUND' is not recognized as an internal or external command,
operable program or batch file.
ninja: build stopped: subcommand failed.

**Comment by schwabe** [comment] 2018-06-11 11:18
Duplicate of #840

**Closed as completed** 2018-06-11 11:17 UTC
